x-services-template: &backend-template
  image: oven/bun:1.2.14
  volumes:
    - ./:/app
  command: bun run dev
  working_dir: /app
  environment:
    - NODE_ENV=development
    - PORT=4000
    - PGHOST=bn-payment-db
    - PGPORT=5432
    - PGDATABASE=bn_payment
    - PGUSERNAME=postgres
    - PGPASSWORD=postgres
    - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    - REDIS_HOST=bn-payment-redis
    - REDIS_PORT=6379
  networks:
    - bn-payment-network
    - payment-processor
  depends_on:
    - postgres
    - redis
  deploy:
    resources:
      limits:
        cpus: "0.3"
        memory: "70MB"

services:
  nginx:
    image: nginx:latest
    container_name: bn-payment-nginx
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bn-payment-network
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  backend-1:
    <<: *backend-template
    container_name: bn-payment-backend-1
    hostname: backend-1

  backend-2:
    <<: *backend-template
    container_name: bn-payment-backend-2
    hostname: backend-2

  postgres:
    image: postgres:15-alpine
    container_name: bn-payment-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bn_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - bn-payment-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  redis:
    image: redis:7-alpine
    container_name: bn-payment-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - bn-payment-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

volumes:
  postgres_data:
    driver: local

networks:
  bn-payment-network:
    name: bn-payment-network
    driver: bridge
  payment-processor:
    external: true
